# Generated by Django 3.1.7 on 2021-02-28 18:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('syntax', models.CharField(choices=[('Bash', 'Bash'), ('C', 'C'), ('C#', 'C Sharp'), ('C++', 'Cpp'), ('CSS', 'Css'), ('HTML', 'Html'), ('JSON', 'Json'), ('Java', 'Java'), ('JavaScript', 'Javascript'), ('Lua', 'Lua'), ('Objective C', 'Objective C'), ('PHP', 'Php'), ('Perl', 'Perl'), ('Python', 'Python'), ('Ruby', 'Ruby'), ('Swift', 'Swift')], max_length=20)),
                ('code', models.TextField()),
                ('link', models.CharField(max_length=8, unique=True)),
            ],
        ),
    ]
